#! /bin/sh
set -e

case "$1" in
  configure)
    echo "deb bootstrap: . main" > /etc/apt/sources.list
    apt-get -o Acquire::Languages=none -o Debug::NoLocking=1 -o APT::Keep-Fds::=4 update 4<>/dev/null
  ;;

  abort-upgrade|abort-remove|abort-deconfigure)
  ;;

  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
  ;;
esac

exit 0
